[project]
name = "17-tools-streamlit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.2.0",
    "numpy>=2.4.3",
    "onnxruntime>=1.24.3",
    "pillow>=12.1.1",
    "streamlit>=1.55.0",
    "streamlit-drawable-canvas>=0.9.3",
]
