[project]
name = "14-dl-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "camelot-py[cv]>=0.11.0",
    "colablinter>=0.1.7",
    "dotenv>=0.9.9",
    "faiss-cpu>=1.13.2",
    "ghostscript>=0.8.1",
    "img2table>=1.4.2",
    "ipykernel>=7.1.0",
    "langchain-community>=0.4.1",
    "langchain-openai>=1.1.7",
    "pdfplumber>=0.11.9",
    "pypdf>=6.6.2",
    "requests>=2.32.5",
    "torch>=2.10.0",
    "transformers>=4.21.0",
]
