# tools:
#   preprocess_and_modeling:
#     image: pixar12372/pre_and_modeling:1.0
#     volumes:

#   predict:
#     image: jupyter/datascience-notebook


services:

  modeling:
    image: pixar12372/pre_and_modeling:1.1
    container_name: researcher_1
    command: bash -lc "
      python main.py 
      && cp /app/data/model/model.pkl /shared/model.pkl 
      && cp /app/data/raw/mission15_test.csv /shared/mission15_test.csv 
      && cp /app/notebooks/main.py /shared/main.py
      && cp /app/requirements.txt /shared/requirements.txt
      && chown -R 1000:100 /shared 
      && chmod -R u+rwX,g+rwX /shared
      "
    volumes:
      - shared_data:/shared

  jupyter:
    image: jupyter/scipy-notebook:python-3.11
    container_name: researcher_2
    command: >
      bash -lc "
      while [ ! -f /shared/requirements.txt ]; do sleep 1; done;
      pip install -r /shared/requirements.txt 
      && start-notebook.py --ServerApp.token='' --ServerApp.password=''
      "
    volumes: 
      - shared_data:/shared
      - shared_data:/home/jovyan/work/shared
    ports:
      - 8888:8888
    depends_on:
      - modeling

volumes:
  shared_data:
